### ISSUE TITLE
download link not working cracker tools 2.6 by yildo

### ISSUE THREAD

**Issue by sajibzzz** [trietptm/x64dbg-Archive#1]
Can you please update the link of cracker tools 2.6 by yildo. the link you proivided is expired.

**Comment by zq3** [comment]
Yes we need yildo download link

**Comment by trietptm** [comment]
I have extracted all x64dbg-related files. If you need other files, please find some forums for your request, thanks.

**Comment by c0c41n3** [comment]
[Cracker Tools 2.8 Free Download](https://disk.yandex.com/d/thW70brYNCceoQ)

**Comment by bernas197** [comment]
Still not working the link
