### ISSUE TITLE
Pls new link

### ISSUE THREAD

**Issue by Z0iruS** [trietptm/x64dbg-Archive#2]
PLs new link :( for 2.6

**Comment by trietptm** [comment]
Sorry, I don't understand your request.

**Comment by 1sp34n** [comment]
link to mega.nz expired, so we need new link to download tools by yildo v2.6 :]

**Comment by trietptm** [comment]
I have extracted all x64dbg-related files. If you need other files, please find some forums for your request, thanks.

**Comment by c0c41n3** [comment]
[Cracker Tools 2.8 Free Download](https://disk.yandex.com/d/thW70brYNCceoQ)
